# Generated by Django 4.1 on 2022-09-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base_user",
            name="Profile_Pic",
            field=models.URLField(blank=True),
        ),
    ]
