# Generated by Django 4.1 on 2022-09-05 15:05

import Users.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_teacher_student"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="teacher",
            managers=[
                ("teacher", Users.models.TeacherManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
