# Generated by Django 4.1 on 2022-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_teacher_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Teachers",
            field=models.ManyToManyField(blank=True, to="Users.teacher"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "student"),
                    ("TEACHER", "Teacher"),
                ],
                max_length=50,
            ),
        ),
    ]
