# Generated by Django 4.1 on 2022-09-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="Teachers",),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RoomName", models.CharField(max_length=250)),
                ("RoomDescription", models.TextField(max_length=1000)),
                (
                    "Owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.teacher"
                    ),
                ),
                ("Students", models.ManyToManyField(to="Users.student")),
            ],
        ),
    ]
