# Generated by Django 4.1 on 2022-09-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("Image1", models.URLField(blank=True)),
                ("Image2", models.URLField(blank=True)),
                ("Image3", models.URLField(blank=True)),
                (
                    "quiz_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Quizzes.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IsCorrect", models.BooleanField()),
                ("Answer", models.TextField(max_length=500)),
                (
                    "QuestionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quizzes.question",
                    ),
                ),
            ],
        ),
    ]
