# Generated by Django 4.1 on 2022-09-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
        ("Quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="AllowedStudents",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.student",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="Quiz_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="Organizer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.teacher",
            ),
        ),
    ]
