# Generated by Django 4.1 on 2022-09-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0002_quiz_allowedstudents_quiz_quiz_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="AllowedStudents",),
    ]
