# Generated by Django 4.1 on 2022-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0003_remove_quiz_allowedstudents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="Quiz_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
