# Generated by Django 4.1 on 2022-09-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
        ("Quizzes", "0004_alter_quiz_quiz_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="Organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.teacher",
            ),
        ),
    ]
