# Generated by Django 4.1 on 2022-09-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0007_rename_organizer_quiz_organizer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quiz_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Quizzes.quiz",
            ),
        ),
    ]
