# Generated by Django 4.1 on 2022-09-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Quizzes", "0009_remove_question_image1_remove_question_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz", old_name="Quiz_name", new_name="Name",
        ),
        migrations.RemoveField(model_name="quiz", name="Organizer_id",),
        migrations.AddField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                default="15",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="Quiz",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
