# Generated by Django 4.1 on 2022-09-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0011_alter_question_quiz_alter_question_image1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="Answer", new_name="answer",
        ),
    ]
