# Generated by Django 4.1 on 2022-09-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
        ("Quizzes", "0012_rename_answer_answer_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=10)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.student"
                    ),
                ),
                (
                    "teache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Users.teacher",
                    ),
                ),
            ],
        ),
    ]
