# Generated by Django 4.1 on 2022-09-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Quizzes", "0013_response"),
    ]

    operations = [
        migrations.RemoveField(model_name="response", name="teache",),
        migrations.AddField(
            model_name="response",
            name="Quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Quizzes.quiz",
            ),
        ),
    ]
