# Generated by Django 4.1 on 2022-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_student_teachers_alter_user_role"),
        ("Quizzes", "0014_remove_response_teache_response_quiz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response", old_name="Quiz", new_name="quiz",
        ),
        migrations.AlterField(
            model_name="response",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.student",
                unique=True,
            ),
        ),
    ]
